-- 1 PASSO:
-- CRIAR A BASE (CREATE SCHEMA OU CREATE DATABASE)
CREATE DATABASE IF NOT EXISTS PROVA_SI1N;
-- IF NOT EXISTES: NÃO CRIA SE JA HOUVER CRIADO


-- PASSO 2 
-- CARREGAR A BASE DE DADOS CRIADA PARA USO
USE PROVA_SI1N;

-- PASSO 3 
-- CRIAR AS TABELAS SEM CHAVE ESTRANGEIRA
CREATE TABLE IF NOT EXISTS ALUNO(
	MATRICULA INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASC DATE NOT NULL


);
CREATE TABLE IF NOT EXISTS PROFESSOR(
MATRICULA INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ESPECIALIZAÇÃO VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS CURSO(
	COD_CURSO INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DURACAO VARCHAR(50) NOT NULL

);

-- PASSO 4 
-- CRIAR AS TABELAS COM CHAVE ESTRANGEIRA 
CREATE TABLE IF NOT EXISTS DISCIPLINA(

	CODIGO INT PRIMARY KEY,
    NOME_DISC VARCHAR(100) NOT NULL,
    CARGA_HORARIO INT NOT NULL,
	COD_CURSO INT NOT NULL,
    CONSTRAINT CUR_DIS FOREIGN KEY(COD_CURSO) references CURSO(COD_CURSO)
    );

-- PASSO 5:
-- CRIAR AS ENTEIDADES ASSOCIADTIVAS, SE HOUVER 

	CREATE TABLE IF NOT EXISTS ALUNOS_DISCIPLINAS(
    MATRICULA INT,
    CODIGO INT,
    PRIMARY KEY(MATRICULA, CODIGO),
    FOREIGN KEY(MATRICULA) REFERENCES ALUNO(MATRICULA),
    FOREIGN KEY (CODIGO) REFERENCES DISCIPLINA(CODIGO));

CREATE TABLE IF NOT EXISTS CURSO_PROFESSOR(
NUM_REG INT,
COD_CURSO INT,
PRIMARY KEY (CODCURSO),
FOREIGN KEY (CODCURSO) REFERENCES PROFESSOR(MATRICULA),
FOREIGN KEY (CODCURSO) REFERENCES CURSO(COD_CURSO),
);
CREATE TABLE IF NOT EXISTS ALUNOS_CURSOS();
